name: scuba_man
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.22.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1

  # For OS-specific directory paths
  path_provider: ^1.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/cheep-green.png
    - assets/images/cheep-white.png
    - assets/images/bg_ocean.png
    - assets/images/title.png
    - assets/images/start_game.png
    - assets/images/quit_game.png
    - assets/images/sprite_sheet_jellyfish.png
    - assets/images/sprite_scuba_man.png
    - assets/images/sprite_sheet_fishy.png
    - assets/images/sprite_sheet_bubble.png
    - assets/images/sprite_sheet_shell.png
    - assets/images/sprite-shark.png
    - assets/images/health_bar_0.png
    - assets/images/health_bar_1.png
    - assets/images/health_bar_2.png
    - assets/images/health_bar_3.png
    - assets/images/swim_left.png
    - assets/images/swim_right.png
    - assets/images/swim_up.png
    - assets/audio/bgm/password_mmx.mp3
    - assets/audio/bgm/ecco_title_gg.mp3
